### ISSUE TITLE
Textfield to Dropdown in Edit profile 

### ISSUE THREAD

**Issue by prateeksingamsetty** [prateeksingamsetty/WolfTrackPlus#1]
In the Edit Profile, the Gender dropdown is TextField whereas it was a dropdown while signing up to the application. Need to change that to DropDown now.

**Comment by khoadangtran** [comment]
Hi, I want to work on this issue, Can you please assign it to me?

**Comment by prateeksingamsetty** [comment]
Changed it to dropdown
![image](https://github.com/prateeksingamsetty/WolfTrackPlus/assets/48323615/4f5bf9bd-7fff-4611-a256-1fd7674fb2aa)
