### ISSUE TITLE
No data displayed after registering

### ISSUE THREAD

**Issue by prateeksingamsetty** [prateeksingamsetty/WolfTrackPlus#2]
**Issue**
Once a user registers, we send them to homepage. The Gender and location details there are not being displayed there in the home page.

**Solution**
->I see that they are rendering to a wrong route here in the py file. Verify that check how to render it to the right route with proper data being sent.

**Comment by laasya2704** [comment]
The bug has been fixed and it is now rendering to the correct route. The required details are now being displayed on the home page.
