### ISSUE TITLE
Redirecting back to login during refresh

### ISSUE THREAD

**Issue by prateeksingamsetty** [prateeksingamsetty/WolfTrackPlus#3]
**Issue**
->When a new user registers, he lands on the home page, but I see that when the page is refreshed, he's being redirected back to the login page. This also seems to be some routing issue in the /signup route.

**Solution Idea**
->Check the signup route and make sure to route it back to a correct route to resolve this issue. Look around to see if there's anything else to be reviewed or changed

**Comment by shiva1239** [comment]
I have fixed this issue when ever a new user registers he will not directly land on home page, I have changed that; at first he will be redirected to the login page and then after entering his credentials in login page he will be moved to home page.

This has fixed the issue, now even if the page is refreshed it still says on the same page.
