### ISSUE TITLE
Data not displayed in view_list.html

### ISSUE THREAD

**Issue by prateeksingamsetty** [prateeksingamsetty/WolfTrackPlus#5]
**Issue**
![image](https://github.com/prateeksingamsetty/WolfTrackPlus/assets/48323615/426e3cb5-f71d-425d-8918-8e2844f051ed)

As shown in the above image, data isn't being displayed for the user. I see the issue is that the data is not being sent in the /view_list route and as a result, there's no data to be displayed in the front end

**Solution idea**
->Just pass the data required in the arguments when the route is being redirected in the backend. This should resolve the issue.

**Comment by shiva1239** [comment]
This is resolved now the thing previously was data not being sent. I have changed that below is the screen shot of the fixed issue.

![Screenshot 2023-11-22 at 3 55 27 PM](https://github.com/prateeksingamsetty/WolfTrackPlus/assets/61696599/d844c679-d3fc-462a-a7d2-b815ef1f802a)
