### ISSUE TITLE
Change Input Type 

### ISSUE THREAD

**Issue by shiva1239** [prateeksingamsetty/WolfTrackPlus#8]
While Adding new applications or editing application for location the input type is textbox instead change that to dropdown which will prevent user from entering incorrect data.

**Comment by prateeksingamsetty** [comment]
Yes Location is now updated with dropdown field.
![image](https://github.com/prateeksingamsetty/WolfTrackPlus/assets/48323615/b048ec50-e451-4b6b-8fee-80d40564422f)
